config/routes.rb
Rails.application.routes.draw do
  resources :entries
  
  get 'welcome/index'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord

  validates :title, presence: true, length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def index
    @entries = Entry.all
  end

  def new
    @entry = Entry.new
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to @entry
    else
      render 'new'
    end
  end


  def show
    @entry = Entry.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])

    if @entry.update(entry_params)
      redirect_to @entry
    else
      render 'edit'
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    redirect_to entries_path
  end

private

  def entry_params
    params.require(:entry).permit(:title, :text)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/_form.html.erb
<%= form_with model: @entry, local: true do |form| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@entry.errors.count, 'error') %>
        Entry could not be saved:
      </h3>
      <ul>
        <%= @entry.errors.full_mssages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title  %>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/entries/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

<%= link_to 'Return to entries', entries_path %>

app/views/entries/index.html.erb
<h1>Entries</h1>
<%= link_to 'New Entry', new_entry_path %>
  <% @entries.each do |entry| %>
      <h3>
        <%= link_to entry.title, entry_path(entry) %>
      </h3>
      <p>
        <%= entry.text %>
      </p>
      <br>
  <% end %>
<br>

app/views/entries/new.html.erb
<h1>New</h1>

<%= render 'form' %>

<%= link_to 'Return', entries_path %>

app/views/entries/show.html.erb
<p>
  <strong>Title</strong><br>
  <%= @entry.title %>
</p>

<p>
  <strong>Text</strong><br>
  <%= @entry.text %>
</p>
<%= link_to 'Edit', edit_entry_path %>

<%= link_to 'Return to Entries', entries_path %>

<%= link_to 'Delete', entry_path(@entry), method: :delete, data: {confirm: 'Are you sure?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fromscratch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to 'Home', controller: 'welcome' %></li>
        <li><%= link_to 'Blog', controller: 'entries' %></li>
        <li><%= link_to 'New post',  'entries/new' %></li>
        <li><a href="#">Projects</a></li>
        <li><a href="#">Contact</a></li>
        <li><a href="#">About</a></li>
      </ul>
    </nav>
    <%= yield %>
    <footer>Est. 2017. Noel Irias</footer>
  </body>
</html>

app/views/welcome/index.html.erb
<%= @entries %>